name:                Stepik-Haskell
version:             0.1.0.0
github:              "razorr1996/stepik_haskell"
license:             BSD3
author:              "Artem Basalaev"
maintainer:          "basa62.1996@gmail.com"
copyright:           "2021 Artem Basalaev"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/razorr1996/stepik_haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - transformers
  - mtl
  - hspec

library:
  source-dirs: src

executables:
  Stepik-Haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Stepik-Haskell
      - transformers
      - mtl

tests:
  Stepik-Haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Stepik-Haskell
      - transformers
      - mtl
      - hspec
      - hspec-discover
